### ISSUE TITLE
Do not remove ECG and add events to EEG structure

### ISSUE THREAD

**Issue by arnodelorme** [amisepa/BrainBeats#17]
It is drastic to remove the ECG channel. Instead keep it by default. Also add the ECG peaks as EEGLAB events.

**Comment by amisepa** [comment]
Which mode? 
It is preserved for removing heart components from EEG data. It is separated into its own structure for HEP and features. 

I'm thinking of adding the option to keep or remove the ECG channel in GUI and users can choose. 

It's necessary to remove it for HEP analysis, otherwise you have ECG signal in your ERP or time-frequency outputs. 

What do you mean by eeglab events? We already have the heartbeats marked as R-peaks in the EEG data (HEP mode).

**Comment by arnodelorme** [comment]
It would be great if people could run the HEP and HRV modes at the same time. Not a super big deal, but definitely a limitation.

**Comment by amisepa** [comment]
Ok, that shouldn't be too hard to change that.

**Comment by amisepa** [comment]
Tricky to run both because of how the toolbox is designed: The EEG preprocessing are slightly different between HEP and features-mode. And for Features, you don't need the ms time synchrony between ECG/PPG and EEG, whereas it is essential for HEP. And HEP and Features are kind of very different applications so not sure it is worth the extra work at the moment. 

I added the option to keep the cardiovascular channels via GUI and command line though.
