### ISSUE TITLE
hrv_features not saved in history when you select it in the GUI

### ISSUE THREAD

**Issue by arnodelorme** [amisepa/BrainBeats#18]

**Comment by amisepa** [comment]
History meaning eegh? Or the actual outputs? 
I had seen them exported properly in the Features output.

**Comment by arnodelorme** [comment]
Yes, eegh

**Comment by amanda-mccleery** [comment]
Hi @arnodelorme @amisepa,  
I am testing out the BrainBeats toolbox and I have a question - where do I find the HRV features output? Also, I receive the following error message: "EEGLAB error in function plot_features() at line 91: Unrecognized function or variable 'EEG' If you think this is a bug..." when I run the HRV analysis using process file (subject level). 

Figures 2 (filtered ECG signal + R peaks, RR intervals, and R events over time) & 3 (PSD HRV, MFE HRV, and a blank plot) are generated, but I don't see output for the HRV feature indices saved anywhere (e.g., a text file with SDNN, etc.).  

Thanks in advance for your assistance and please let me know if you need additional information to help me resolve the EEGLAB error message and locate the output file.

**Comment by amanda-mccleery** [comment]
![Fig 2](https://github.com/amisepa/BrainBeats/assets/135731751/5dac7a10-9784-4bf7-aff3-f67aef157dc3)
![Fig 3](https://github.com/amisepa/BrainBeats/assets/135731751/6fcf817f-c018-4fd2-86b1-e2a877aa1fb2)

**Comment by amisepa** [comment]
Hi,

Did you install BrainBeats from the GitHub repo (unzip or cloning) or from the eeglab extension manager? If form GitHub, HRV features are stored in the 'EEG.features' structure (eeglab structure) of your file. Otherwise they are also saved in a Matlab structure in the same place as your file you loaded in eeglab. So if you go in the folder where you loaded your file, you should see a Matlab file called Features.mat 
(and make sure the save option is selected in parameters).

The 'EEG' error might be a bug yes when you don't select EEG features. And the blank area is for the EEG plots so that's why they're blank. I need to update the code adjust the figure for this situation. You may select EEG time features to avoid the error for now, and it's very fast to compute so it won't add time. 

Cedric

**Comment by amanda-mccleery** [comment]
To view restingstate_eo_wecg_features.mat, sign in<https://iowa-my.sharepoint.com/:u:/g/personal/amccleery_uiowa_edu/EYBGezrbR6lPltGF0vlZEfgBnHNpXEHGxmRZxCLC8GMhmg> or create an account.

**Comment by amanda-mccleery** [comment]
Hi, 
I added BrainBeats through the EEGlab extension manager. I see the features.mat file, but when I try to load the file in matlab nothing happens. How do you view the output from the features.mat file (e.g., import into in EEGlab, export to a text file, etc.)?

**Comment by amanda-mccleery** [comment]
Nevermind - I think I've got it!
Thanks so much for your help -  I will keep playing with the toolbox and will let you know if I have any questions or encounter error messages

**Comment by amisepa** [comment]
Ok. They're stored in the structures by domain: time, frequency, nonlinear. 
You can plot the same plots with plot_features(Features);

You can easily export as a csv file like this for example for SDNN
writetable(struct2table(Features.time.SDNN),'SDNN.csv');

**Comment by amanda-mccleery** [comment]
Excellent - thanks so much!

**Comment by amisepa** [comment]
And you should use the more recent version from GitHub, some issues were fixed

**Comment by amanda-mccleery** [comment]
Will do re: Github version

**Comment by amanda-mccleery** [comment]
Hi @amisepa I installed BrainBeats from Github and encountered this error message: 

![image](https://github.com/amisepa/BrainBeats/assets/135731751/828e8690-6ee0-4449-aca0-015a248c72e9)

**Comment by amisepa** [comment]
Ah sorry.. that a from a recent merge and isn't have time to test. I'll try to fix it in the next few days.

**Comment by amanda-mccleery** [comment]
No worries and thank you!
